# Generated by Django 5.2.5 on 2025-09-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingresa titulo del libro', max_length=50)),
                ('nombre_autor', models.CharField(help_text='Ingresa nombre del autor del libro', max_length=50)),
                ('saga', models.CharField()),
            ],
        ),
    ]
