# Generated by Django 5.2.5 on 2025-09-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='libro',
            table='Libro',
        ),
    ]
