# Generated by Django 5.2.5 on 2025-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0002_alter_libro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(help_text='Ingresa una sinopsis del libro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='saga',
            field=models.CharField(help_text='¿Es el libro parte de una saga?'),
        ),
    ]
