# Generated by Django 5.2.5 on 2025-09-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0003_alter_libro_options_libro_sinopsis_alter_libro_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
