# Generated by Django 5.2.5 on 2025-09-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0005_categoria_cliente_pedido_producto_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reads.categoria'),
        ),
    ]
