# Generated by Django 5.2.5 on 2025-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0007_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='linkGoodreads',
            field=models.URLField(blank=True, help_text='Link del libro en Goodreads', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_autor',
            field=models.CharField(help_text='Ingresa nombre del autor del libro', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='saga',
            field=models.BooleanField(default=False, help_text='¿Es el libro parte de una saga?'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, help_text='Ingresa una sinopsis del libro', null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(help_text='Ingresa título del libro', max_length=100),
        ),
    ]
