# Generated by Django 5.2.5 on 2025-09-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0009_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='Contacto',
        ),
    ]
