# Generated by Django 5.2.5 on 2025-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0010_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='calificacion_trama',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 ⭐'), (1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=0, verbose_name='Calificación trama'),
        ),
        migrations.AddField(
            model_name='libro',
            name='nivel_spicy',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 🌶️'), (1, '1 🌶️'), (2, '2 🌶️'), (3, '3 🌶️'), (4, '4 🌶️'), (5, '5 🌶️')], default=0, verbose_name='Nivel Spicy'),
        ),
    ]
