# Generated by Django 5.2.5 on 2025-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0011_libro_calificacion_trama_libro_nivel_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='calificacion_trama',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nivel_spicy',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
