# Generated by Django 5.2.5 on 2025-09-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0012_alter_libro_calificacion_trama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_saga',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de libros en la saga', null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='saga_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la saga (si aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='saga_terminada',
            field=models.BooleanField(default=False, help_text='¿La saga está terminada?'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='calificacion_trama',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Calificación de la trama (1 a 5)'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Selecciona la categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reads.categoria'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, help_text='Fecha de publicación del libro', null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nivel_spicy',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Nivel de spicy (1 a 5)'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, help_text='Sube una portada para el libro', null=True, upload_to='portadas/'),
        ),
    ]
